// Regenerates src/abi.ts from the Foundry build (run `forge build` in the repo root first).
//   npm run abi
import { readFileSync, writeFileSync } from 'node:fs'

const root = new URL('../../', import.meta.url)
const read = (path: string): unknown[] => JSON.parse(readFileSync(new URL(path, root), 'utf8')).abi

const aiArbiter = read('out/AIArbiter.sol/AIArbiter.json')
const rentEscrow = read('out/IRentEscrow.sol/IRentEscrow.json')

const out = `// GENERATED by scripts/gen-abi.ts from the Foundry build of ../src. Do not edit by hand.
// Regenerate: (cd .. && forge build) && npm run abi

export const aiArbiterAbi = ${JSON.stringify(aiArbiter, null, 2)} as const

export const rentEscrowAbi = ${JSON.stringify(rentEscrow, null, 2)} as const

/** RentoutsSubnames (ens/ package, deployed on Sepolia): the one view the judge needs. */
export const rentoutsSubnamesAbi = [
  {
    type: 'function',
    name: 'nameOf',
    stateMutability: 'view',
    inputs: [{ name: 'holder', type: 'address' }],
    outputs: [{ name: '', type: 'string' }],
  },
] as const
`
writeFileSync(new URL('src/abi.ts', new URL('../', import.meta.url)), out)
console.log('wrote src/abi.ts')
